tasks:
  - before: export DANGEROUSLY_DISABLE_HOST_CHECK
    init: yarn && composer install
    command: yarn serve

vscode:
  extensions:
    - mohamedbenhida.laravel-intellisense@0.1.9:AMiQsKd2+jC1TRtDYlVA3A==
    - ikappas.composer@0.7.1:BR1vLGzI+4Z+CXzwcWtKIw==